In [1]:
# ===============（a）===================
# 解下列方程组
import numpy as np
a1 = np.array(
[
    [3, -2, -5, 1],
    [2, -3, 1, 5],
    [1, 2, 0, -4],
    [1, -1, -4, 9]
])
b1 = np.array([
    [3],
    [-3],
    [-3],
    [22]
])
a1

array([[ 3, -2, -5,  1],
       [ 2, -3,  1,  5],
       [ 1,  2,  0, -4],
       [ 1, -1, -4,  9]])

In [2]:
b1

array([[ 3],
       [-3],
       [-3],
       [22]])

In [3]:
x1 = np.linalg.solve(a1,b1)
x1
# 这里使用了numpy中linalg模块求解线性方程组的解：np.linalg.solve(A,b)
# 也可以使用sympy包的方法，以后将会以sympy方法为主。

array([[-1.],
       [ 3.],
       [-2.],
       [ 2.]])

In [4]:
# ===============（b）===================
# 解下列方程组
a2 = np.array(
[
    [2, -2, 0, 1, 3],
    [2, 3, 1, -3, 6],
    [3, 4, -1, 2, 0],
    [1, 3, 1, -1, -2]
])
b2 = np.zeros((4,1))
b2

array([[0.],
       [0.],
       [0.],
       [0.]])

In [5]:
a2

array([[ 2, -2,  0,  1,  3],
       [ 2,  3,  1, -3,  6],
       [ 3,  4, -1,  2,  0],
       [ 1,  3,  1, -1, -2]])

In [8]:
from sympy import Matrix
mat2_a2 = Matrix(a2)
mat2_a2

Matrix([
[2, -2,  0,  1,  3],
[2,  3,  1, -3,  6],
[3,  4, -1,  2,  0],
[1,  3,  1, -1, -2]])

In [10]:
mat2_b2 = Matrix(b2)
mat2_b2

Matrix([
[0.0],
[0.0],
[0.0],
[0.0]])

In [21]:
mat2_aug = Matrix([[mat2_a2, mat2_b2]])
mat2_aug
# 生成增广矩阵

Matrix([
[2, -2,  0,  1,  3, 0.0],
[2,  3,  1, -3,  6, 0.0],
[3,  4, -1,  2,  0, 0.0],
[1,  3,  1, -1, -2, 0.0]])

In [23]:
mat2_simp = mat2_aug.rref()
mat2_simp[0]

Matrix([
[1, 0, 0, 0,  2, 0],
[0, 1, 0, 0, -1, 0],
[0, 0, 1, 0, -4, 0],
[0, 0, 0, 1, -3, 0]])

In [26]:
mat2_simp[0][:,4]
# 方程组为欠定方程组，当x5=1时，第五列为方程组x1~x4的解

Matrix([
[ 2],
[-1],
[-4],
[-3]])

In [27]:
# ===============（c）===================
# 解下列方程组
a3 = Matrix([[1, 1, -6, -4],
            [3, -1, -6, -4],
            [2, 3, 9, 2],
            [3, 2, 3, 8]])
a3

Matrix([
[1,  1, -6, -4],
[3, -1, -6, -4],
[2,  3,  9,  2],
[3,  2,  3,  8]])

In [39]:
b3 = Matrix([[6],[2],[6],[-7]])
b3

Matrix([
[ 6],
[ 2],
[ 6],
[-7]])

In [40]:
mat3_aug = Matrix([[a3,b3]])
mat3_simp = mat3_aug.rref()
mat3_simp[0]

Matrix([
[1, 0, 0, 0,    0],
[0, 1, 0, 0,    2],
[0, 0, 1, 0,  1/3],
[0, 0, 0, 1, -3/2]])

In [41]:
mat3_simp[0][:,4]

Matrix([
[   0],
[   2],
[ 1/3],
[-3/2]])